name         'tmont-redis'
version      '0.1.0'
author       'Thomas Van Doren'
license      'BSD'
project_page 'https://github.com/tmont/puppet-redis'
dependency   'puppetlabs/gcc'
dependency   'puppetlabs/stdlib'
